spring.application.name=SPEL_DEMO

# Patient info and Test Prizing
digo.name=Vikram
digo.age=22
digo.mri=1500
digo.ctscan=2000
digo.dibetic=1000
digo.bp=500

#Custom properties file 
spring.config.import=com/vik/commons/info.properties


