spring.application.name=ConfigurationPropertiesDemo

#Person details 
person.info.name=Vikram
person.info.age=22
person.info.city=pune
person.info.homeaddress=Argade Gavhan Jalna 
person.info.education=BCA
person.info.phonenumaber=9577014555
person.info.email=vikramgujar300@gmail.com
