spring.application.name=ConfigurationPropertiesDemo

#Person details 
person.info.name=Vikram
person.info.age=22
person.info.city=pune
person.info.homeaddress=Argade Gavhan Jalna 
person.info.education=BCA
person.info.phonenumaber=9577014555
person.info.email=vikramgujar300@gmail.com

#Insert Arraylist Collection Property
person.info.niknames=Vikram Dada,Viku,Viky
# OR you can insert arraylist property one by one 
#person.info.niknames[0]=Vikram Dada
#person.info.niknames[1]=Viku
#person.info.niknames[2]=Viky

#Insert Map Collection
#This will be inserted as key and value pair 
person.info.favorites.cricketer=Virat
person.info.favorites.character=Iron-Man
person.info.favorites.actor=RDJ

#Insert Array type Data
person.info.friends=Vaibhav,Suraj,Kalpesh,Pavan

#Insert data to Object type 
person.info.details.name=Vikram
person.info.details.age=22
person.info.details.number=9577014555
person.info.details.mail=vikramgujar300@gmail.com



